src/Entity/Servicos.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ServicosRepository")
 */
class Servicos
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\column(type="string")
     */
    private $tipo;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $descricao;

    /**
     * @ORM\Column(type="integer")
     */
    private $tempo_medio;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->tipo;
    }

    public function setTipo(string $tipo): self
    {
        $this->tipo = $tipo;

        return $this;
    }

    public function getDescricao(): ?string
    {
        return $this->descricao;
    }

    public function setDescricao(string $descricao): self
    {
        $this->descricao = $descricao;

        return $this;
    }

    public function getTempoMedio(): ?int
    {
        return $this->tempo_medio;
    }

    public function setTempoMedio(int $tempo_medio): self
    {
        $this->tempo_medio = $tempo_medio;

        return $this;
    }

    public function __toString() {
        return $this->getDescricao();
    }
}

src/Form/ServicosType.php
<?php

namespace App\Form;

use App\Entity\Servicos;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ServicosType extends AbstractType
{
    private $enum_tipo = array('Hidraulico'=>'Hidraulico', 'Eletrico'=>'Eletrico', 'Pintura'=>'Pintura');

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('tipo', ChoiceType::class, ['choices'  => [$this->enum_tipo], 'placeholder' => 'Tipo'])
        ->add('descricao')
            ->add('tempo_medio')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Servicos::class,
        ]);
    }

    public function getEnumTipo(){
        return $this->enum_tipo;
    }
}

src/Controller/ServicosController.php
<?php

namespace App\Controller;

use App\Entity\Servicos;
use App\Form\ServicosType;
use App\Repository\ServicosRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/servicos")
 */
class ServicosController extends AbstractController
{
    /**
     * @Route("/", name="servicos_index", methods={"GET"})
     */
    public function index(ServicosRepository $servicosRepository): Response
    {
        return $this->render('servicos/index.html.twig', [
            'servicos' => $servicosRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="servicos_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $servico = new Servicos();
        $servicosRepository = $this->getDoctrine()->getRepository(Servicos::class);
        $form = $this->createForm(ServicosType::class, $servico);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $valid = $servicosRepository->validaForm($request->request->get('servicos'));

            if($valid === true){
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($servico);
                $entityManager->flush();
                return $this->redirectToRoute('servicos_index');
            } else{
                return $this->render('servicos/new.html.twig', [
                    'servico' => $servico,
                    'form' => $form->createView(),
                    'erro' => $valid,
                ]);
            }

            
        }

        return $this->render('servicos/new.html.twig', [
            'servico' => $servico,
            'form' => $form->createView(),
            'erro' => false,
        ]);
    }

    /**
     * @Route("/{id}", name="servicos_show", methods={"GET"})
     */
    public function show(Servicos $servico): Response
    {
        return $this->render('servicos/show.html.twig', [
            'servico' => $servico,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="servicos_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Servicos $servico): Response
    {
        $form = $this->createForm(ServicosType::class, $servico);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('servicos_index', [
                'id' => $servico->getId(),
            ]);
        }

        return $this->render('servicos/edit.html.twig', [
            'servico' => $servico,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="servicos_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Servicos $servico): Response
    {
        if ($this->isCsrfTokenValid('delete'.$servico->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($servico);
            $entityManager->flush();
        }

        return $this->redirectToRoute('servicos_index');
    }
}

templates/servicos/_delete_form.html.twig
<form method="post" action="{{ path('servicos_delete', {'id': servico.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ servico.id) }}">
    <button class="btn">Delete</button>
</form>

templates/servicos/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/servicos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Servicos{% endblock %}

{% block body %}
    <h1>Edit Servicos</h1>

    {{ include('servicos/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('servicos_index') }}">back to list</a>

    {{ include('servicos/_delete_form.html.twig') }}
{% endblock %}

templates/servicos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Servicos index{% endblock %}

{% block body %}
    <h1>Servicos index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Tipo</th>
                <th>Descricao</th>
                <th>Tempo_medio</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for servico in servicos %}
            <tr>
                <td>{{ servico.id }}</td>
                <td>{{ servico.tipo }}</td>
                <td>{{ servico.descricao }}</td>
                <td>{{ servico.tempoMedio }}</td>
                <td>
                    <a href="{{ path('servicos_show', {'id': servico.id}) }}">show</a>
                    <a href="{{ path('servicos_edit', {'id': servico.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('servicos_new') }}">Create new</a>
{% endblock %}

templates/servicos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Servicos{% endblock %}

{% block body %}
    <h1>Create new Servicos</h1>

    {{ include('servicos/_form.html.twig') }}

    <a href="{{ path('servicos_index') }}">back to list</a>

    {% if erro %}
        <br><h4>{{erro}}</h4>
    {% endif %}
{% endblock %}

templates/servicos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Servicos{% endblock %}

{% block body %}
    <h1>Servicos</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ servico.id }}</td>
            </tr>
            <tr>
                <th>Tipo</th>
                <td>{{ servico.tipo }}</td>
            </tr>
            <tr>
                <th>Descricao</th>
                <td>{{ servico.descricao }}</td>
            </tr>
            <tr>
                <th>Tempo_medio</th>
                <td>{{ servico.tempoMedio }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('servicos_index') }}">back to list</a>

    <a href="{{ path('servicos_edit', {'id': servico.id}) }}">edit</a>

    {{ include('servicos/_delete_form.html.twig') }}
{% endblock %}