src/Entity/Os.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OsRepository")
 */
class Os
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=13)
     */
    private $Sequence;

    /**
     * @ORM\Column(type="float")
     */
    private $desconto;

    /**
     * @ORM\Column(type="float")
     */
    private $valor_total;

    /**
     * @ORM\Column(type="datetime")
     */
    private $data_servico;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Tecnicos", inversedBy="Os")
     * @ORM\JoinColumn(nullable=false, name="tecnico_id", referencedColumnName="id")
     */
    private $tecnico;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ferramentas", mappedBy="Os")
     */
    private $ferramenta;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Servicos", inversedBy="Os")
     * @ORM\JoinColumn(nullable=false, name="servico_id", referencedColumnName="id")
     */
    private $servico;

    public function __construct()
    {
        $this->ferramenta = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSequence(): ?string
    {
        return $this->Sequence;
    }

    public function setSequence(string $Sequence): self
    {
        $this->Sequence = $Sequence;

        return $this;
    }

    public function getDesconto(): ?float
    {
        return $this->desconto;
    }

    public function setDesconto(float $desconto): self
    {
        $this->desconto = $desconto;

        return $this;
    }

    public function getValorTotal(): ?float
    {
        return $this->valor_total;
    }

    public function setValorTotal(float $valor_total): self
    {
        $this->valor_total = $valor_total;

        return $this;
    }

    public function getDataServico(): ?\DateTimeInterface
    {
        return $this->data_servico;
    }

    public function setDataServico(\DateTimeInterface $data_servico): self
    {
        $this->data_servico = $data_servico;

        return $this;
    }

    public function getTecnico(): ?Tecnicos
    {
        return $this->tecnico;
    }

    public function setTecnico(?Tecnicos $tecnico): self
    {
        $this->tecnico = $tecnico;

        return $this;
    }

    /**
     * @return Collection|ferramentas[]
     */
    public function getFerramenta(): Collection
    {
        return $this->ferramenta;
    }

    public function addFerramentum(Ferramentas $ferramentum): self
    {
        if (!$this->ferramenta->contains($ferramentum)) {
            $this->ferramenta[] = $ferramentum;
            $ferramentum->setOs($this);
        }

        return $this;
    }

    public function removeFerramentum(ferramentas $ferramentum): self
    {
        if ($this->ferramenta->contains($ferramentum)) {
            $this->ferramenta->removeElement($ferramentum);
            // set the owning side to null (unless already changed)
            if ($ferramentum->getOs() === $this) {
                $ferramentum->setOs(null);
            }
        }

        return $this;
    }

    public function getServico(): ?Servicos
    {
        return $this->servico;
    }

    public function setServico(?Servicos $servico): self
    {
        $this->servico = $servico;

        return $this;
    }
}

src/Form/OsType.php
<?php

namespace App\Form;

use App\Entity\Os;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // ->add('Sequence')
            ->add('desconto')
            // ->add('valor_total')
            ->add('data_servico')
            ->add('tecnico')
            ->add('ferramenta')
            ->add('servico')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Os::class,
        ]);
    }
}

src/Controller/OsController.php
<?php

namespace App\Controller;

use App\Entity\Os;
use App\Form\OsType;
use App\Repository\OsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/os")
 */
class OsController extends AbstractController
{
    /**
     * @Route("/", name="os_index", methods={"GET"})
     */
    public function index(OsRepository $osRepository): Response
    {
        return $this->render('os/index.html.twig', [
            'os' => $osRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="os_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $o = new Os();
        $osRepository = $this->getDoctrine()->getRepository(Os::class);
        $form = $this->createForm(OsType::class, $o);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $o = $osRepository->prepareForm($request->request->get('os'),$o);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($o);
            $entityManager->flush();

            return $this->redirectToRoute('os_index');
        }

        return $this->render('os/new.html.twig', [
            'o' => $o,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="os_show", methods={"GET"})
     */
    public function show(Os $o): Response
    {
        return $this->render('os/show.html.twig', [
            'o' => $o,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="os_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Os $o): Response
    {
        $form = $this->createForm(OsType::class, $o);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('os_index', [
                'id' => $o->getId(),
            ]);
        }

        return $this->render('os/edit.html.twig', [
            'o' => $o,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="os_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Os $o): Response
    {
        if ($this->isCsrfTokenValid('delete'.$o->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($o);
            $entityManager->flush();
        }

        return $this->redirectToRoute('os_index');
    }
}

templates/os/_delete_form.html.twig
<form method="post" action="{{ path('os_delete', {'id': o.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ o.id) }}">
    <button class="btn">Delete</button>
</form>

templates/os/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/os/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Os{% endblock %}

{% block body %}
    <h1>Edit Os</h1>

    {{ include('os/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('os_index') }}">back to list</a>

    {{ include('os/_delete_form.html.twig') }}
{% endblock %}

templates/os/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Os index{% endblock %}

{% block body %}
    <h1>Os index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Sequence</th>
                <th>Desconto</th>
                <th>Valor_total</th>
                <th>Data_servico</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for o in os %}
            <tr>
                <td>{{ o.id }}</td>
                <td>{{ o.Sequence }}</td>
                <td>{{ o.desconto }}</td>
                <td>{{ o.valorTotal }}</td>
                <td>{{ o.dataServico ? o.dataServico|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('os_show', {'id': o.id}) }}">show</a>
                    <a href="{{ path('os_edit', {'id': o.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('os_new') }}">Create new</a>
{% endblock %}

templates/os/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Os{% endblock %}

{% block body %}
    <h1>Create new Os</h1>

    {{ include('os/_form.html.twig') }}

    <a href="{{ path('os_index') }}">back to list</a>
{% endblock %}

templates/os/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Os{% endblock %}

{% block body %}
    <h1>Os</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ o.id }}</td>
            </tr>
            <tr>
                <th>Sequence</th>
                <td>{{ o.Sequence }}</td>
            </tr>
            <tr>
                <th>Desconto</th>
                <td>{{ o.desconto }}</td>
            </tr>
            <tr>
                <th>Valor_total</th>
                <td>{{ o.valorTotal }}</td>
            </tr>
            <tr>
                <th>Data_servico</th>
                <td>{{ o.dataServico ? o.dataServico|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('os_index') }}">back to list</a>

    <a href="{{ path('os_edit', {'id': o.id}) }}">edit</a>

    {{ include('os/_delete_form.html.twig') }}
{% endblock %}