src/Entity/Ferramentas.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FerramentasRepository")
 */
class Ferramentas
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $cod_ferramenta;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $nome_ferramenta;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $marca_ferramenta;

    /**
     * @ORM\Column(type="float")
     */
    private $aluguel_hora;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Os", inversedBy="Ferramenta")
     */
    private $os;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodFerramenta(): ?int
    {
        return $this->cod_ferramenta;
    }

    public function setCodFerramenta(int $cod_ferramenta): self
    {
        $this->cod_ferramenta = $cod_ferramenta;

        return $this;
    }

    public function getNomeFerramenta(): ?string
    {
        return $this->nome_ferramenta;
    }

    public function setNomeFerramenta(string $nome_ferramenta): self
    {
        $this->nome_ferramenta = $nome_ferramenta;

        return $this;
    }

    public function getMarcaFerramenta(): ?string
    {
        return $this->marca_ferramenta;
    }

    public function setMarcaFerramenta(string $marca_ferramenta): self
    {
        $this->marca_ferramenta = $marca_ferramenta;

        return $this;
    }

    public function getAluguelHora(): ?float
    {
        return $this->aluguel_hora;
    }

    public function setAluguelHora(float $aluguel_hora): self
    {
        $this->aluguel_hora = $aluguel_hora;

        return $this;
    }

    public function getOs(): ?Os
    {
        return $this->os;
    }

    public function setOs(?Os $os): self
    {
        $this->os = $os;

        return $this;
    }

    public function __toString() {
        return $this->getNomeFerramenta();
    }
}

src/Form/FerramentasType.php
<?php

namespace App\Form;

use App\Entity\Ferramentas;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FerramentasType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // ->add('cod_ferramenta')
            ->add('nome_ferramenta')
            ->add('marca_ferramenta')
            ->add('aluguel_hora')
            // ->add('os')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ferramentas::class,
        ]);
    }
}

src/Controller/FerramentasController.php
<?php

namespace App\Controller;

use App\Entity\Ferramentas;
use App\Form\FerramentasType;
use App\Repository\FerramentasRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ferramentas")
 */
class FerramentasController extends AbstractController
{
    /**
     * @Route("/", name="ferramentas_index", methods={"GET"})
     */
    public function index(FerramentasRepository $ferramentasRepository): Response
    {
        return $this->render('ferramentas/index.html.twig', [
            'ferramentas' => $ferramentasRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ferramentas_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ferramenta = new Ferramentas();
        $ferramentasRepository = $this->getDoctrine()->getRepository(Ferramentas::class);
        $form = $this->createForm(FerramentasType::class, $ferramenta);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $ferramenta = $ferramentasRepository->prepareForm($request->request->get('ferramentas'),$ferramenta);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ferramenta);
            $entityManager->flush();

            return $this->redirectToRoute('ferramentas_index');
        }

        return $this->render('ferramentas/new.html.twig', [
            'ferramenta' => $ferramenta,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ferramentas_show", methods={"GET"})
     */
    public function show(Ferramentas $ferramenta): Response
    {
        return $this->render('ferramentas/show.html.twig', [
            'ferramenta' => $ferramenta,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ferramentas_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Ferramentas $ferramenta): Response
    {
        $form = $this->createForm(FerramentasType::class, $ferramenta);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ferramentas_index', [
                'id' => $ferramenta->getId(),
            ]);
        }

        return $this->render('ferramentas/edit.html.twig', [
            'ferramenta' => $ferramenta,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ferramentas_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Ferramentas $ferramenta): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ferramenta->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ferramenta);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ferramentas_index');
    }
}

templates/ferramentas/_delete_form.html.twig
<form method="post" action="{{ path('ferramentas_delete', {'id': ferramenta.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ferramenta.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ferramentas/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/ferramentas/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ferramentas{% endblock %}

{% block body %}
    <h1>Edit Ferramentas</h1>

    {{ include('ferramentas/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('ferramentas_index') }}">back to list</a>

    {{ include('ferramentas/_delete_form.html.twig') }}
{% endblock %}

templates/ferramentas/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ferramentas index{% endblock %}

{% block body %}
    <h1>Ferramentas index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Cod_ferramenta</th>
                <th>Nome_ferramenta</th>
                <th>Marca_ferramenta</th>
                <th>Aluguel_hora</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ferramenta in ferramentas %}
            <tr>
                <td>{{ ferramenta.id }}</td>
                <td>{{ ferramenta.codFerramenta }}</td>
                <td>{{ ferramenta.nomeFerramenta }}</td>
                <td>{{ ferramenta.marcaFerramenta }}</td>
                <td>{{ ferramenta.aluguelHora }}</td>
                <td>
                    <a href="{{ path('ferramentas_show', {'id': ferramenta.id}) }}">show</a>
                    <a href="{{ path('ferramentas_edit', {'id': ferramenta.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('ferramentas_new') }}">Create new</a>
{% endblock %}

templates/ferramentas/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ferramentas{% endblock %}

{% block body %}
    <h1>Create new Ferramentas</h1>

    {{ include('ferramentas/_form.html.twig') }}

    <a href="{{ path('ferramentas_index') }}">back to list</a>
{% endblock %}

templates/ferramentas/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ferramentas{% endblock %}

{% block body %}
    <h1>Ferramentas</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ferramenta.id }}</td>
            </tr>
            <tr>
                <th>Cod_ferramenta</th>
                <td>{{ ferramenta.codFerramenta }}</td>
            </tr>
            <tr>
                <th>Nome_ferramenta</th>
                <td>{{ ferramenta.nomeFerramenta }}</td>
            </tr>
            <tr>
                <th>Marca_ferramenta</th>
                <td>{{ ferramenta.marcaFerramenta }}</td>
            </tr>
            <tr>
                <th>Aluguel_hora</th>
                <td>{{ ferramenta.aluguelHora }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('ferramentas_index') }}">back to list</a>

    <a href="{{ path('ferramentas_edit', {'id': ferramenta.id}) }}">edit</a>

    {{ include('ferramentas/_delete_form.html.twig') }}
{% endblock %}