src/Entity/Tecnicos.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TecnicosRepository")
 */
class Tecnicos
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=11)
     */
    private $cpf;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $nome_completo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dt_nasc;

    /**
     * @ORM\Column(type="float")
     */
    private $valor_hora;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Os", mappedBy="Tecnico")
     */
    private $os;

    public function __construct()
    {
        $this->os = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCpf(): ?string
    {
        return $this->cpf;
    }

    public function setCpf(string $cpf): self
    {
        $this->cpf = $cpf;

        return $this;
    }

    public function getNomeCompleto(): ?string
    {
        return $this->nome_completo;
    }

    public function setNomeCompleto(string $nome_completo): self
    {
        $this->nome_completo = $nome_completo;

        return $this;
    }

    public function getDtNasc(): ?\DateTimeInterface
    {
        return $this->dt_nasc;
    }

    public function setDtNasc(\DateTimeInterface $dt_nasc): self
    {
        $this->dt_nasc = $dt_nasc;

        return $this;
    }

    public function getValorHora(): ?float
    {
        return $this->valor_hora;
    }

    public function setValorHora(float $valor_hora): self
    {
        $this->valor_hora = $valor_hora;

        return $this;
    }

    /**
     * @return Collection|Os[]
     */
    public function getOs(): Collection
    {
        return $this->os;
    }

    public function addO(Os $o): self
    {
        if (!$this->os->contains($o)) {
            $this->os[] = $o;
            $o->setTecnico($this);
        }

        return $this;
    }

    public function removeO(Os $o): self
    {
        if ($this->os->contains($o)) {
            $this->os->removeElement($o);
            // set the owning side to null (unless already changed)
            if ($o->getTecnico() === $this) {
                $o->setTecnico(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return $this->getNomeCompleto();
    }
}

src/Form/TecnicosType.php
<?php

namespace App\Form;

use App\Entity\Tecnicos;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TecnicosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('cpf')
            ->add('nome_completo')
            ->add('dt_nasc')
            ->add('valor_hora')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tecnicos::class,
        ]);
    }
}

src/Controller/TecnicosController.php
<?php

namespace App\Controller;

use App\Entity\Tecnicos;
use App\Form\TecnicosType;
use App\Repository\TecnicosRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tecnicos")
 */
class TecnicosController extends AbstractController
{
    /**
     * @Route("/", name="tecnicos_index", methods={"GET"})
     */
    public function index(TecnicosRepository $tecnicosRepository): Response
    {
        return $this->render('tecnicos/index.html.twig', [
            'tecnicos' => $tecnicosRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="tecnicos_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $tecnico = new Tecnicos();
        $tecnicosRepository = $this->getDoctrine()->getRepository(Tecnicos::class);
        $form = $this->createForm(TecnicosType::class, $tecnico);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $valid = $tecnicosRepository->validaForm($request->request->get('tecnicos'));

            if($valid === true){
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($tecnico);
                $entityManager->flush();
                return $this->redirectToRoute('tecnicos_index');
            } else{
                return $this->render('tecnicos/new.html.twig', [
                    'tecnico' => $tecnico,
                    'form' => $form->createView(),
                    'erro' => $valid,
                ]);
            } 
        }

        return $this->render('tecnicos/new.html.twig', [
            'tecnico' => $tecnico,
            'form' => $form->createView(),
            'erro' => false,
        ]);
    }

    /**
     * @Route("/{id}", name="tecnicos_show", methods={"GET"})
     */
    public function show(Tecnicos $tecnico): Response
    {
        return $this->render('tecnicos/show.html.twig', [
            'tecnico' => $tecnico,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="tecnicos_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tecnicos $tecnico): Response
    {
        $form = $this->createForm(TecnicosType::class, $tecnico);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('tecnicos_index', [
                'id' => $tecnico->getId(),
            ]);
        }

        return $this->render('tecnicos/edit.html.twig', [
            'tecnico' => $tecnico,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tecnicos_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tecnicos $tecnico): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tecnico->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($tecnico);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tecnicos_index');
    }
}

templates/tecnicos/_delete_form.html.twig
<form method="post" action="{{ path('tecnicos_delete', {'id': tecnico.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tecnico.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tecnicos/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tecnicos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tecnicos{% endblock %}

{% block body %}
    <h1>Edit Tecnicos</h1>

    {{ include('tecnicos/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('tecnicos_index') }}">back to list</a>

    {{ include('tecnicos/_delete_form.html.twig') }}
{% endblock %}

templates/tecnicos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tecnicos index{% endblock %}

{% block body %}
    <h1>Tecnicos index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Cpf</th>
                <th>Nome_completo</th>
                <th>Dt_nasc</th>
                <th>Valor_hora</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tecnico in tecnicos %}
            <tr>
                <td>{{ tecnico.id }}</td>
                <td>{{ tecnico.cpf }}</td>
                <td>{{ tecnico.nomeCompleto }}</td>
                <td>{{ tecnico.dtNasc ? tecnico.dtNasc|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ tecnico.valorHora }}</td>
                <td>
                    <a href="{{ path('tecnicos_show', {'id': tecnico.id}) }}">show</a>
                    <a href="{{ path('tecnicos_edit', {'id': tecnico.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('tecnicos_new') }}">Create new</a>
{% endblock %}

templates/tecnicos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tecnicos{% endblock %}

{% block body %}
    <h1>Create new Tecnicos</h1>

    {{ include('tecnicos/_form.html.twig') }}

    <a href="{{ path('tecnicos_index') }}">back to list</a>

    {% if erro %}
        <br><h4>{{erro}}</h4>
    {% endif %}
{% endblock %}

templates/tecnicos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tecnicos{% endblock %}

{% block body %}
    <h1>Tecnicos</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tecnico.id }}</td>
            </tr>
            <tr>
                <th>Cpf</th>
                <td>{{ tecnico.cpf }}</td>
            </tr>
            <tr>
                <th>Nome_completo</th>
                <td>{{ tecnico.nomeCompleto }}</td>
            </tr>
            <tr>
                <th>Dt_nasc</th>
                <td>{{ tecnico.dtNasc ? tecnico.dtNasc|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Valor_hora</th>
                <td>{{ tecnico.valorHora }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('tecnicos_index') }}">back to list</a>

    <a href="{{ path('tecnicos_edit', {'id': tecnico.id}) }}">edit</a>

    {{ include('tecnicos/_delete_form.html.twig') }}
{% endblock %}